config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :screenshots, only: [:new, :create, :edit, :update, :destroy]
  resources :reports
  resources :exploits do
    get :autocomplete_exploit_platform_title, on: :collection
    get :autocomplete_exploit_type_title, on: :collection
  end

  resources :customers, only: [:index, :show] do
    get :autocomplete_customer_name, :on => :collection
  end

  resources :cves, only: [:show, :index]
  resources :exploit_types, only: [:show]
  resources :exploit_platforms, only: [:show]
  resources :exploit_authors, only: [:show]
  resources :exploit_search, only: [:index]
  resources :custom_exploits, only: [:index]
  resources :nmap
  resources :engagements do
    collection do
      get 'download'
    end
    member do
      put :complete
      get :vuln_details
      get :iava
    end
    resources :ocbs, only: [:create]
    resources :nmap, only: [:new, :create, :show] do
      resources :nmap_reports, only: [:index]
    end
    resources :engagement_creds, only: [:create, :destroy, :index]
    resources :engagement_mains, only: [:create, :destroy, :update, :index] do
      resources :host_vulns, only: [:create, :update, :destroy]
      resources :engagement_main_users, only: [:index, :create]
      resources :host_creds, only: [:create, :update, :destroy]
      resources :custom_findings, only: [:create, :update, :destroy]
    end
    resources :nessus, only: [:new, :create, :show] do
      resources :nessus_reports, only: [:index]
      resources :vulns_reports, only: [:index]
    end
    resources :host_scan_details, only: [:show]
    resources :hosts, only: [:show] do
      resources :host_services, only: [:create, :update, :destroy]
    end
    resources :metasploit, only: [:new, :create, :show] do
      resources :metasploit_reports, only: [:index]
    end
    resources :metasploit_host_views, only: [:show]
  end

  resources :engagement_statuses do
    member do
      post :accept
    end
  end
  resources :notes, only: [:create, :destroy]
  resources :on_hold_engagements, only: [:show]
  resources :activate_engagements, only: [:show]
  resources :end_engagements, only: [:update]
  resources :cwes, only: [:show, :index]
  resources :cwe_categories, only: [:show]
  resources :cwe_compound_elements, only: [:show]

  get 'download_exploit/download/:id' => 'download_exploit#download', as: :download_exploit
  get '/reports/:id/penetrations/new' => 'reports#new_penetration', as: :add_new_penetration
  delete '/reports/:id/penetrations/:penetration_id' => 'reports#remove_penetration', as: :remove_penetration
  get 'reports/:id/pdf' => 'reports#get_pdf', as: :get_pdf

  root 									 'static_pages#home'
  get 'signup'				=> 'users#new'
  get	'admin'					=> 'settings#edit'
  get 'login'		  		=> 'sessions#new'

  get 'users/get_stats'			 => 'users#get_stats'
  get 'user/:id/reset_password' => 'users#reset_password', as: :reset_user_password

  post 'login' 		 			=> 'sessions#create'
  post 'join'           => 'teams#join'
  post 'remove_member'  => 'teams#remove_member'

  delete 'logout'					=> 'sessions#destroy'

  patch 'settings' => 'settings#update'
  resources :teams do
    get 'add_members'
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    collection do
      get 'find_users'
    end
  end
  resources :users
  resources :teams
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/engagements/:engagement_id/hosts/:host_id/evidences/list' => 'evidences#list'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/upload' => 'evidences#upload'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/rename' => 'evidences#rename'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/copy' => 'evidences#copy'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/move' => 'evidences#move'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/remove' => 'evidences#remove'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/edit' => 'evidences#edit'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/get_content' => 'evidences#get_content'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/create_folder' => 'evidences#create_folder'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download' => 'evidences#download'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download_multiple' => 'evidences#download_multiple'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/compress' => 'evidences#compress'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/extract' => 'evidences#extract'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/permissions' => 'evidences#permissions'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/setting.rb
class ValidateDates < ActiveModel::Validator
  def validate(record)
    if record.setting_type == 'date' && !DateTime.strptime(record.value, '%m/%d/%Y %I:%M %p')
      record.errors[] << 'Invalid date'
    end
  end
end

class Setting < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :setting_type, presence: true, length: { maximum: 255 }
  validates_with ValidateDates
end

app/models/team.rb
class Team < ActiveRecord::Base
	include SettingsHelper
	has_many :users, dependent: :destroy, inverse_of: :team
	validates :name,  presence: true, length: { maximum: 50 },
										uniqueness: true
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	before_action :admin_user, only: [:index, :edit, :update]

	def edit
		# Ordering General first, then all others
		@categories = ["General"]
		@categories += Setting.where.not(category: 'General').distinct.pluck(:category).sort

		@general = Setting.where(category: 'General').order(id: :asc)
		@other_settings = Setting.where.not(category: 'General').order(category: :asc, id: :asc)
		@settings = @general + @other_settings

		@users = User.all
		@users_without_team = User.where(team_id: nil)
		@teams = Team.all
	end

	def update
		error = false
		settings = params[:admin]

		settings.each do |key, setting|
			to_update = Setting.find(setting[:id])

			if to_update.setting_type == 'boolean'
				to_update.value = (setting[:value]) ? "1" : "0"
			else
				to_update.value = setting[:value]
			end

			error = (to_update.save) ? false : true
		end

		if error
			flash[:danger] = "Failed to update database. Try again."
		else
			flash[:success] = "Successfully updated changes."
		end
		redirect_to admin_url
	end

	private
	def admin_user
		unless logged_in? && current_user.admin?
			store_location
			flash[:danger] = "Access Denied."
			redirect_to root_url
		end
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
	def competition_started?
		start_time = DateTime.strptime(Setting.find_by(name: 'start_time').value, '%m/%d/%Y %I:%M %p')
		DateTime.current.to_i > start_time.to_i
	end

	def competition_ended?
		end_time = DateTime.strptime(Setting.find_by(name: 'end_time').value, '%m/%d/%Y %I:%M %p')
		DateTime.current.to_i > end_time.to_i
	end

	def competition_active?
		competition_started? && !competition_ended?
	end

	def vapt_project
		Setting.find_by(name: 'vapt_project').try(:value) || ''
	end

	def view_other_profiles?
		(Setting.find_by(name: 'view_other_profiles').try(:value) == "0") ? false : true
	end

end

app/views/settings/_form.html.erb
 <!-- Nav tabs -->
    <%= content_tag :ul, class: 'nav nav-tabs', role: 'tablist' do %>
        <%= content_tag :li do %>
            <%= content_tag :a, 'Teams', href: "#teams", 'aria-controls' => "teams", role: 'tab', 'data-toggle' => 'tab' %>
        <% end %>
        <%= content_tag :li do %>
            <%= content_tag :a, 'Users', href: "#users", 'aria-controls' => "users", role: 'tab', 'data-toggle' => 'tab' %>
        <% end %>

        <%= content_tag :div, id: 'filter_container', class: 'input-group pull-right', style: 'display:none' do %>
            <%= content_tag :span, 'Search', class: 'input-group-addon' %>
            <input id="filter" type="text" class="filter form-control">
        <% end %>
    <% end %>

    <!-- Tab panes -->
    <%= content_tag :div, class: 'tab-content' do %>

        <%= content_tag :div, class: 'tab-pane', id: 'teams' do %>
            <%= content_tag :h4, "Count: #{@teams.count}", class: 'text-center' %>
            <%= content_tag :ul, class: 'teams row filter_list' do %>
                <%= render partial: 'teams/team', collection: @teams, locals: { num_challenges: @num_challenges } %>
            <% end %>
            <%= form_for(Team.new, url: teams_path(), method: :post) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <%= f.label "Team Name"  %>
                <%= f.text_field :name, class: 'form-control' %>
                <br/>
                <%= f.label "Add Users to Team" %>
                <%= select_tag 'user_ids', options_from_collection_for_select(@users_without_team, "id", "full_name"), multiple: true, class: 'form-control chosen-it' %>
                <br/>
                <%= f.submit "Create Team", class: "btn btn-primary" %>
            <% end %>
        <% end %>
        <%= content_tag :div, class: 'tab-pane', id: 'users' do %>
            <%= content_tag :h4, "Count: #{@users.count}", class: 'text-center' %>
            <%= content_tag :ul, class: 'users row filter_list' do %>
                <%= render @users %>
            <% end %>
        <% end %>
    <% end %>

app/views/settings/_setting.html.erb
<% ######################################################################### %>
<% # This is essentially a switch statement.  The type of setting          # %>
<% # determines how it is rednered.                                        # %>
<% ######################################################################### %>
<%= content_tag :div, class: 'row settings-row' do %>

  <% # Switches for boolean settings # %>
  <% if setting.setting_type == 'boolean' %>
    <%= hidden_field_tag "admin[#{setting.id.to_s}][id]", :id, value: setting.id %>
    <%= content_tag :div, class: 'col-md-4' do %>
      <%= label_tag nil, setting.label, class: 'control-label' %>
      <%= tag :br %>
      <%= content_tag :small, simple_format(setting.tooltip), class: 'text-muted' %>
    <% end %>
    <%  checked = (setting.value == '1') ? true : false %>
    <%= check_box_tag "admin[#{setting.id.to_s}][value]", setting.value, checked, class: 'col-md-8 bootstrap-switches' %>

  <% # Color picker for 'color' settings # %>
  <% #elsif setting.setting_type == 'color' %>

  <% # Datetime picker for 'date' settings # %>
  <% elsif setting.setting_type == 'date' %>
    <%= hidden_field_tag "admin[#{setting.id.to_s}][id]", :id, value: setting.id %>
    <%= content_tag :div, class: 'col-md-4' do %>
      <%= label_tag nil, setting.label, class: 'control-label' %>
      <%= tag :br %>
      <%= content_tag :small, simple_format(setting.tooltip), class: 'text-muted' %>
    <% end %>

  <% # Text box for standard text settings # %>
  <% else #setting.setting_type == 'text' %>
    <%= hidden_field_tag "admin[#{setting.id.to_s}][id]", :id, value: setting.id %>
    <%= content_tag :div, class: 'col-md-4' do %>
      <%= label_tag nil, setting.label, class: 'control-label' %>
      <%= tag :br %>
      <%= content_tag :small, simple_format(setting.tooltip), class: 'text-muted' %>
    <% end %>
    <%= text_field "admin[#{setting.id.to_s}]", 'value', value: setting.value, class: 'col-md-8 form-control' %>
  <% end %>
<% end %>

app/views/settings/edit.html.erb
<% provide(:title, 'Admin Console') %>
<%= content_tag :h1, 'Settings' %>
<%= content_tag :div, id: 'settings', class: 'row' do %>
    <%= render 'form' %>
<% end %>