config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :screenshots, only: [:new, :create, :edit, :update, :destroy]
  resources :reports
  resources :exploits do
    get :autocomplete_exploit_platform_title, on: :collection
    get :autocomplete_exploit_type_title, on: :collection
  end

  resources :customers, only: [:index, :show] do
    get :autocomplete_customer_name, :on => :collection
  end

  resources :cves, only: [:show, :index]
  resources :exploit_types, only: [:show]
  resources :exploit_platforms, only: [:show]
  resources :exploit_authors, only: [:show]
  resources :exploit_search, only: [:index]
  resources :custom_exploits, only: [:index]
  resources :nmap
  resources :engagements do
    collection do
      get 'download'
    end
    member do
      put :complete
      get :vuln_details
      get :iava
    end
    resources :ocbs, only: [:create]
    resources :nmap, only: [:new, :create, :show] do
      resources :nmap_reports, only: [:index]
    end
    resources :engagement_creds, only: [:create, :destroy, :index]
    resources :engagement_mains, only: [:create, :destroy, :update, :index] do
      resources :host_vulns, only: [:create, :update, :destroy]
      resources :engagement_main_users, only: [:index, :create]
      resources :host_creds, only: [:create, :update, :destroy]
      resources :custom_findings, only: [:create, :update, :destroy]
    end
    resources :nessus, only: [:new, :create, :show] do
      resources :nessus_reports, only: [:index]
      resources :vulns_reports, only: [:index]
    end
    resources :host_scan_details, only: [:show]
    resources :hosts, only: [:show] do
      resources :host_services, only: [:create, :update, :destroy]
    end
    resources :metasploit, only: [:new, :create, :show] do
      resources :metasploit_reports, only: [:index]
    end
    resources :metasploit_host_views, only: [:show]
  end

  resources :engagement_statuses do
    member do
      post :accept
    end
  end
  resources :notes, only: [:create, :destroy]
  resources :on_hold_engagements, only: [:show]
  resources :activate_engagements, only: [:show]
  resources :end_engagements, only: [:update]
  resources :cwes, only: [:show, :index]
  resources :cwe_categories, only: [:show]
  resources :cwe_compound_elements, only: [:show]

  get 'download_exploit/download/:id' => 'download_exploit#download', as: :download_exploit
  get '/reports/:id/penetrations/new' => 'reports#new_penetration', as: :add_new_penetration
  delete '/reports/:id/penetrations/:penetration_id' => 'reports#remove_penetration', as: :remove_penetration
  get 'reports/:id/pdf' => 'reports#get_pdf', as: :get_pdf

  root 									 'static_pages#home'
  get 'signup'				=> 'users#new'
  get	'admin'					=> 'settings#edit'
  get 'login'		  		=> 'sessions#new'

  get 'users/get_stats'			 => 'users#get_stats'
  get 'user/:id/reset_password' => 'users#reset_password', as: :reset_user_password

  post 'login' 		 			=> 'sessions#create'
  post 'join'           => 'teams#join'
  post 'remove_member'  => 'teams#remove_member'

  delete 'logout'					=> 'sessions#destroy'

  patch 'settings' => 'settings#update'
  resources :teams do
    get 'add_members'
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    collection do
      get 'find_users'
    end
  end
  resources :users
  resources :teams
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/engagements/:engagement_id/hosts/:host_id/evidences/list' => 'evidences#list'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/upload' => 'evidences#upload'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/rename' => 'evidences#rename'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/copy' => 'evidences#copy'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/move' => 'evidences#move'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/remove' => 'evidences#remove'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/edit' => 'evidences#edit'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/get_content' => 'evidences#get_content'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/create_folder' => 'evidences#create_folder'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download' => 'evidences#download'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download_multiple' => 'evidences#download_multiple'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/compress' => 'evidences#compress'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/extract' => 'evidences#extract'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/permissions' => 'evidences#permissions'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/controllers/nessus_controller.rb
class NessusController < ApplicationController
  
  before_action :logged_in_user
  
  
	def new
	end

	def create
	  engagement = Engagement.find(params[:engagement_id])
    engagement_file = engagement.engagement_files.new(user_id: current_user.id, asset: params[:nessus_file])
    
    if engagement_file.save
      NessusWorker.perform_async(engagement_file.id, engagement.id, current_user.id)
      
      flash.now[:notice] = 'Nessus file uploaded and will be processed on the background.'      
  		redirect_to engagement_path(engagement)
    else
			flash.now[:danger] = 'Please select a nessus file.'
			render 'new'
    end
    
    
    # system "risu #{params[:nessus_file].tempfile.path} #{current_user.id} #{params[:engagement_id]}"
    # system "cd ../.."
    
    # output = []
    # IO.popen("risu --config-file #{Rails.root.to_s}/risu.cfg #{params[:nessus_file].tempfile.path} #{current_user.id} #{params[:engagement_id]}").each do |line|
    #   output << line.chomp
    # end
    #
    # @nessus_policy = Risu::Models::Policy.where(engagement_id: params[:engagement_id], user_id: current_user.id).order("id DESC").first || Risu::Models::Policy.first
    #
    # # nessus_hosts = @nessus_policy.nessus_reports.map {|r| r.hosts}.flatten
    # em = PopulateEngagementMain.new(@nessus_policy, current_user.id, params[:engagement_id])
    # em.populate
    
    # redirect_to engagement_nessu_path(params[:engagement_id], @nessus_policy.id)
	end

	def show
		@nessus_policies = Policy.includes(:family_selections, :individual_plugin_selections, :plugins_preferences, :server_preferences, nessus_reports: [hosts: [:host_properties, :items]]).where(engagement_id: params[:engagement_id])
		@plugins = Plugin.includes(:references).all
    @engagement = Engagement.find(params[:engagement_id])
	end
end

app/views/nessus/new.html.erb
<%= content_tag :h1 do %>
	Upload Nessus File
<% end %>
<%= form_tag engagement_nessus_path, multipart: true do %>
	<%= content_tag :div, class: 'row' do %>
		<%= content_tag :div, class: 'col-md-4 col-md-offset-4' do %>
			<%= label_tag "Upload nessus file" %>
			<%= file_field_tag "nessus_file" %>
			<%= submit_tag "Submit", class: "nessus_submit" %>
		<% end %>
	<% end %>
<% end %>

app/views/nessus/show.html.erb
<div class="row">
	<div class="col-md-6 mBot9">
		<%= link_to "Back to #{@engagement.engagement_name}", engagement_path(params[:engagement_id]), class: "btn btn-primary" %>
	</div>
	<div class="col-md-6">
		<%= link_to "Add new nessus", new_engagement_nessu_path(params[:engagement_id]), class: "btn btn-primary policiesRight" %>
	</div>
</div>

<h3>Policies</h3>
<table class="table table-striped table-bordered" id="policies">
	<thead>
		<th>Name</th>
		<th>Comments</th>
		<th>Owner</th>
		<th>Visibility</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<tr>
				<td><%= nessus_policy.name %></td>
				<td><%= nessus_policy.comments %></td>
				<td><%= nessus_policy.owner %></td>
				<td><%= nessus_policy.visibility %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3>Family Selections</h3>
<table class="table table-striped table-bordered" id="family_selections">
	<thead>
		<th>Family Name</th>
		<th>Status</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<% nessus_policy.family_selections.each do |family_selection| %>
				<tr>
					<td><%= family_selection.family_name %></td>
					<td><%= family_selection.status %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

<h3>Hosts</h3>
<table class="table table-striped table-bordered" id="hosts">
	<thead>
		<th>Name</th>
		<th>OS</th>
		<th>MAC</th>
		<th>Start Date</th>
		<th>End Date</th>
		<th>IP</th>
		<th>FQDN</th>
		<th>Netbios</th>
		<th>Notes</th>
		<th>Risk Score</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<% nessus_policy.nessus_reports.each do |report| %>
				<% report.hosts.each do |host| %>
					<tr>
						<td><%= host.name %></td>
						<td><%= host.os %></td>
						<td><%= host.mac %></td>
						<td><%= host.start %></td>
						<td><%= host.end %></td>
						<td><%= host.ip %></td>
						<td><%= host.fqdn %></td>
						<td><%= host.netbios %></td>
						<td><%= host.notes %></td>
						<td><%= host.risk_score %></td>
					</tr>
				<% end %>
			<% end %>
		<% end %>
	</tbody>
</table>

<h3>Host Properties</h3>
<table class="table table-striped table-bordered" id="host_properties">
	<thead>
		<th>Name</th>
		<th>Value</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<% nessus_policy.nessus_reports.each do |report| %>
				<% report.hosts.each do |host| %>
					<% host.host_properties.each do |host_property| %>
						<% unless host_property.name.blank? && host_property.value.blank? %>
							<tr>
								<td><%= host_property.name %></td>
								<td><%= host_property.value %></td>
							</tr>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	</tbody>
</table>

<h3>Individual Plugin Selection</h3>
<table class="table table-striped table-bordered" id="individual_plugin_selection">
	<thead>
		<th>Plugin ID</th>
		<th>Plugin Name</th>
		<th>Family</th>
		<th>Status</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<% nessus_policy.individual_plugin_selections.each do |individual_plugin_selection| %>
				<tr>
					<td><%= individual_plugin_selection.plugin_id %></td>
					<td><%= individual_plugin_selection.plugin_name %></td>
					<td><%= individual_plugin_selection.family %></td>
					<td><%= individual_plugin_selection.status %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

<h3>Items</h3>
<table class="table table-striped table-bordered" id="items">
	<thead>
		<th>Plugin ID</th>
		<th>Plugin Output</th>
		<th>Port</th>
		<th>SVC Name</th>
		<th>Protocol</th>
		<th>Secerity</th>
		<th>Plugin Name</th>
		<th>Verified</th>
		<th>CM Compliance Info</th>
		<th>CM Compliance Actual Value</th>
		<th>CM Compliance Check ID</th>
		<th>CM Compliance Policy Value</th>
		<th>CM Compliance Audit File</th>
		<th>CM Compliance Check Name</th>
		<th>CM Compliance Result</th>
		<th>CM Compliance Output</th>
		<th>CM Compliance Reference</th>
		<th>CM Compliance See Also</th>
		<th>CM Compliance Solution</th>
		<th>Real Severity</th>
		<th>Risk Score</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<% nessus_policy.nessus_reports.each do |report| %>
				<% report.hosts.each do |host| %>
					<% host.items.each do |item| %>
						<tr>
							<td><%= item.plugin_id %></td>
							<td><%= item.plugin_output %></td>
							<td><%= item.port %></td>
							<td><%= item.svc_name %></td>
							<td><%= item.protocol %></td>
							<td><%= item.severity %></td>
							<td><%= item.plugin_name %></td>
							<td><%= item.verified %></td>
							<td><%= item.cm_compliance_info %></td>
							<td><%= item.cm_compliance_actual_value %></td>
							<td><%= item.cm_compliance_check_id %></td>
							<td><%= item.cm_compliance_policy_value %></td>
							<td><%= item.cm_compliance_audit_file %></td>
							<td><%= item.cm_compliance_check_name %></td>
							<td><%= item.cm_compliance_result %></td>
							<td><%= item.cm_compliance_output %></td>
							<td><%= item.cm_compliance_reference %></td>
							<td><%= item.cm_compliance_see_also %></td>
							<td><%= item.cm_compliance_solution %></td>
							<td><%= item.real_severity %></td>
							<td><%= item.risk_score %></td>
						</tr>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	</tbody>
</table>

<h3>Plugins</h3>
<table class="table table-striped table-bordered" id="plugins">
	<thead>
		<th>Plugin Name</th>
		<th>Family Name</th>
		<th>Description</th>
		<th>Plugin Version</th>
		<th>Plugin Publication Date</th>
		<th>Plugin Modification Date</th>
		<th>Vulnerability Publication Date</th>
		<th>CVSS Vector</th>
		<th>CVSS Base Score</th>
		<th>CVSS Temporal Score</th>
		<th>CVSS Temporal Vector</th>
		<th>Exploitability Ease</th>
		<th>Exploit Framework Core</th>
		<th>Exploit Framework Metasploit</th>
		<th>Metasploit Name</th>
		<th>Exploit Framework Canvas</th>
		<th>Canvas Package</th>
		<th>Exploit Available</th>
		<th>Risk Factor</th>
		<th>Solution</th>
		<th>Synopsis</th>
		<th>Plugin Type</th>
		<th>Exploit Framework Exploithub</th>
		<th>Exploithub SKU</th>
		<th>Stig severity</th>
		<th>Fname</th>
		<th>Always Run</th>
		<th>Script Version</th>
		<th>D2 Elliot Name</th>
		<th>Exploit Framework D2 Elliot</th>
		<th>Exploited By Malware</th>
		<th>Rollup</th>
		<th>Risk Score</th>
		<th>Compliance</th>
		<th>Root Cause</th>
		<th>Agent</th>
		<th>Potential Vulnerability</th>
		<th>In The News</th>
		<th>Exploited By Nessus</th>
		<th>Unsupported By Vendor</th>
		<th>Default Account</th>
	</thead>
	<tbody>
		<% @plugins.each do |plugin| %>
			<tr>
				<td><%= plugin.plugin_name %></td>
				<td><%= plugin.family_name %></td>
				<td><%= plugin.description %></td>
				<td><%= plugin.plugin_version %></td>
				<td><%= plugin.plugin_publication_date %></td>
				<td><%= plugin.plugin_modification_date %></td>
				<td><%= plugin.vuln_publication_date %></td>
				<td><%= plugin.cvss_vector %></td>
				<td><%= plugin.cvss_base_score %></td>
				<td><%= plugin.cvss_temporal_score %></td>
				<td><%= plugin.cvss_temporal_vector %></td>
				<td><%= plugin.exploitability_ease %></td>
				<td><%= plugin.exploit_framework_core %></td>
				<td><%= plugin.exploit_framework_metasploit %></td>
				<td><%= plugin.metasploit_name %></td>
				<td><%= plugin.exploit_framework_canvas %></td>
				<td><%= plugin.canvas_package %></td>
				<td><%= plugin.exploit_available %></td>
				<td><%= plugin.risk_factor %></td>
				<td><%= plugin.solution %></td>
				<td><%= plugin.synopsis %></td>
				<td><%= plugin.plugin_type %></td>
				<td><%= plugin.exploit_framework_exploithub %></td>
				<td><%= plugin.exploithub_sku %></td>
				<td><%= plugin.stig_severity %></td>
				<td><%= plugin.fname %></td>
				<td><%= plugin.always_run %></td>
				<td><%= plugin.script_version %></td>
				<td><%= plugin.d2_elliot_name %></td>
				<td><%= plugin.exploit_framework_d2_elliot %></td>
				<td><%= plugin.exploited_by_malware %></td>
				<td><%= plugin.rollup %></td>
				<td><%= plugin.risk_score %></td>
				<td><%= plugin.compliance %></td>
				<td><%= plugin.root_cause %></td>
				<td><%= plugin.agent %></td>
				<td><%= plugin.potential_vulnerability %></td>
				<td><%= plugin.in_the_news %></td>
				<td><%= plugin.exploited_by_nessus %></td>
				<td><%= plugin.unsupported_by_vendor %></td>
				<td><%= plugin.default_account %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3>Plugin Preferences</h3>
<table class="table table-striped table-bordered" id="plugin_preferences">
	<thead>
		<th>Plugin ID</th>
		<th>Plugin Name</th>
		<th>Full Name</th>
		<th>Preference Name</th>
		<th>Preference Type</th>
		<th>Preference Values</th>
		<th>Selected Values</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<% nessus_policy.plugins_preferences.each do |plugin_preference| %>
				<tr>
					<td><%= plugin_preference.plugin_id %></td>
					<td><%= plugin_preference.plugin_name %></td>
					<td><%= plugin_preference.fullname %></td>
					<td><%= plugin_preference.preference_name %></td>
					<td><%= plugin_preference.preference_type %></td>
					<td><%= plugin_preference.preference_values %></td>
					<td><%= plugin_preference.selected_values %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

<h3>References</h3>
<table class="table table-striped table-bordered" id="references">
	<thead>
		<th>Reference Name</th>
		<th>Value</th>
	</thead>
	<tbody>
		<% @plugins.each do |plugin| %>
			<% plugin.references.each do |reference| %>
				<tr>
					<td><%= reference.reference_name %></td>
					<td><%= reference.value %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

<h3>Server Preferences</h3>
<table class="table table-striped table-bordered" id="server_preferences">
	<thead>
		<th>Name</th>
		<th>Value</th>
	</thead>
	<tbody>
		<% @nessus_policies.each do |nessus_policy| %>
			<% nessus_policy.server_preferences.each do |server_preference| %>
				<tr>
					<td><%= server_preference.name %></td>
					<td><%= server_preference.value %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>