config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :screenshots, only: [:new, :create, :edit, :update, :destroy]
  resources :reports
  resources :exploits do
    get :autocomplete_exploit_platform_title, on: :collection
    get :autocomplete_exploit_type_title, on: :collection
  end

  resources :customers, only: [:index, :show] do
    get :autocomplete_customer_name, :on => :collection
  end

  resources :cves, only: [:show, :index]
  resources :exploit_types, only: [:show]
  resources :exploit_platforms, only: [:show]
  resources :exploit_authors, only: [:show]
  resources :exploit_search, only: [:index]
  resources :custom_exploits, only: [:index]
  resources :nmap
  resources :engagements do
    collection do
      get 'download'
    end
    member do
      put :complete
      get :vuln_details
      get :iava
    end
    resources :ocbs, only: [:create]
    resources :nmap, only: [:new, :create, :show] do
      resources :nmap_reports, only: [:index]
    end
    resources :engagement_creds, only: [:create, :destroy, :index]
    resources :engagement_mains, only: [:create, :destroy, :update, :index] do
      resources :host_vulns, only: [:create, :update, :destroy]
      resources :engagement_main_users, only: [:index, :create]
      resources :host_creds, only: [:create, :update, :destroy]
      resources :custom_findings, only: [:create, :update, :destroy]
    end
    resources :nessus, only: [:new, :create, :show] do
      resources :nessus_reports, only: [:index]
      resources :vulns_reports, only: [:index]
    end
    resources :host_scan_details, only: [:show]
    resources :hosts, only: [:show] do
      resources :host_services, only: [:create, :update, :destroy]
    end
    resources :metasploit, only: [:new, :create, :show] do
      resources :metasploit_reports, only: [:index]
    end
    resources :metasploit_host_views, only: [:show]
  end

  resources :engagement_statuses do
    member do
      post :accept
    end
  end
  resources :notes, only: [:create, :destroy]
  resources :on_hold_engagements, only: [:show]
  resources :activate_engagements, only: [:show]
  resources :end_engagements, only: [:update]
  resources :cwes, only: [:show, :index]
  resources :cwe_categories, only: [:show]
  resources :cwe_compound_elements, only: [:show]

  get 'download_exploit/download/:id' => 'download_exploit#download', as: :download_exploit
  get '/reports/:id/penetrations/new' => 'reports#new_penetration', as: :add_new_penetration
  delete '/reports/:id/penetrations/:penetration_id' => 'reports#remove_penetration', as: :remove_penetration
  get 'reports/:id/pdf' => 'reports#get_pdf', as: :get_pdf

  root 									 'static_pages#home'
  get 'signup'				=> 'users#new'
  get	'admin'					=> 'settings#edit'
  get 'login'		  		=> 'sessions#new'

  get 'users/get_stats'			 => 'users#get_stats'
  get 'user/:id/reset_password' => 'users#reset_password', as: :reset_user_password

  post 'login' 		 			=> 'sessions#create'
  post 'join'           => 'teams#join'
  post 'remove_member'  => 'teams#remove_member'

  delete 'logout'					=> 'sessions#destroy'

  patch 'settings' => 'settings#update'
  resources :teams do
    get 'add_members'
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    collection do
      get 'find_users'
    end
  end
  resources :users
  resources :teams
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/engagements/:engagement_id/hosts/:host_id/evidences/list' => 'evidences#list'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/upload' => 'evidences#upload'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/rename' => 'evidences#rename'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/copy' => 'evidences#copy'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/move' => 'evidences#move'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/remove' => 'evidences#remove'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/edit' => 'evidences#edit'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/get_content' => 'evidences#get_content'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/create_folder' => 'evidences#create_folder'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download' => 'evidences#download'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download_multiple' => 'evidences#download_multiple'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/compress' => 'evidences#compress'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/extract' => 'evidences#extract'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/permissions' => 'evidences#permissions'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
	mount_uploader :file, PictureUploader
  belongs_to :report
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_action :set_screenshot, only: [:show, :edit, :update, :destroy]
  before_action :ensure_report_and_vulnerability_present_for_new, only: :new

  # GET /screenshots/new
  def new
    @screenshot = Screenshot.new
  end

  # GET /screenshots/1/edit
  def edit
  end

  # POST /screenshots
  # POST /screenshots.json
  def create
    @screenshot = Screenshot.new(screenshot_params)

    respond_to do |format|
      if @screenshot.save
        format.html { render :close_window, notice: 'Screenshot was successfully created.' }
        format.json { render :show, status: :created, location: @screenshot }
      else
        format.html { render :new }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screenshots/1
  # PATCH/PUT /screenshots/1.json
  def update
    respond_to do |format|
      if @screenshot.update(screenshot_params)
        format.html { redirect_to most_recent_report, notice: 'Screenshot was successfully updated.' }
        format.json { render :show, status: :ok, location: @screenshot }
      else
        format.html { render :edit }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenshots/1
  # DELETE /screenshots/1.json
  def destroy
    @screenshot.destroy
    respond_to do |format|
      format.html { redirect_to most_recent_report, notice: 'Screenshot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def most_recent_report
      report = Report.where(user_id: current_user).last

      if report
        edit_report_path(report)
      else
        reports_path
      end
    end

    def ensure_report_and_vulnerability_present_for_new
      if params[:vulnerability_id].blank?
        redirect_to most_recent_report, notice: 'Please be sure the report and vulnerability are present (click "Add Screenshot" while editing a report).'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_screenshot
      @screenshot = Screenshot.find(params[:id])
      redirect_to most_recent_report if Report.find(@screenshot.report_id).user != current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screenshot_params
      params.require(:screenshot).permit(:file, :report_id, :vulnerability_id, :index, :caption)
    end
end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

app/views/screenshots/_form.html.erb
<%= form_for(@screenshot) do |f| %>
  <% if @screenshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screenshot.errors.count, "error") %> prohibited this screenshot from being saved:</h2>

      <ul>
      <% @screenshot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file, "Screenshot" %><br>
    <%= f.file_field :file, accept: 'image/jpeg,image/gif,image/png', required: true %>
  </div>

  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>

  <%= f.hidden_field :report_id, value: params['report_id'] %>
  <%= f.hidden_field :vulnerability_id, value: params['vulnerability_id'] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screenshots/close_window.html.erb
<h4 style="color: green;">Screenshot uploaded successfully.</h4>

<h3>The screenshots will appear the next time you reload the report.</h3>
<h3>Be sure to save any changes in progress first!</h3>

<br>
<h4>Please close this window to return to your report.</h4>

app/views/screenshots/edit.html.erb
<h1>Editing Screenshot</h1>

<%= render 'form' %>

<%= link_to 'Show', @screenshot %> |
<%= link_to 'Back', screenshots_path %>

app/views/screenshots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Screenshots</h1>

<table>
  <thead>
    <tr>
      <th>File</th>
      <th>Report</th>
      <th>Vulnerability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screenshots.each do |screenshot| %>
      <tr>
        <td><%= screenshot.file %></td>
        <td><%= screenshot.report_id %></td>
        <td><%= screenshot.vulnerability_id %></td>
        <td><%= link_to 'Show', screenshot %></td>
        <td><%= link_to 'Edit', edit_screenshot_path(screenshot) %></td>
        <td><%= link_to 'Destroy', screenshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screenshot', new_screenshot_path %>

app/views/screenshots/new.html.erb
<h1>New Screenshot</h1>

<%= render 'form' %>

app/views/screenshots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= @screenshot.file %>
</p>

<p>
  <strong>Report:</strong>
  <%= @screenshot.report_id %>
</p>

<p>
  <strong>Vulnerability:</strong>
  <%= @screenshot.vulnerability_id %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @screenshot.caption %>
</p>

<%= link_to 'Edit', edit_screenshot_path(@screenshot) %> |
<%= link_to 'Back', screenshots_path %>