config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :screenshots, only: [:new, :create, :edit, :update, :destroy]
  resources :reports
  resources :exploits do
    get :autocomplete_exploit_platform_title, on: :collection
    get :autocomplete_exploit_type_title, on: :collection
  end

  resources :customers, only: [:index, :show] do
    get :autocomplete_customer_name, :on => :collection
  end

  resources :cves, only: [:show, :index]
  resources :exploit_types, only: [:show]
  resources :exploit_platforms, only: [:show]
  resources :exploit_authors, only: [:show]
  resources :exploit_search, only: [:index]
  resources :custom_exploits, only: [:index]
  resources :nmap
  resources :engagements do
    collection do
      get 'download'
    end
    member do
      put :complete
      get :vuln_details
      get :iava
    end
    resources :ocbs, only: [:create]
    resources :nmap, only: [:new, :create, :show] do
      resources :nmap_reports, only: [:index]
    end
    resources :engagement_creds, only: [:create, :destroy, :index]
    resources :engagement_mains, only: [:create, :destroy, :update, :index] do
      resources :host_vulns, only: [:create, :update, :destroy]
      resources :engagement_main_users, only: [:index, :create]
      resources :host_creds, only: [:create, :update, :destroy]
      resources :custom_findings, only: [:create, :update, :destroy]
    end
    resources :nessus, only: [:new, :create, :show] do
      resources :nessus_reports, only: [:index]
      resources :vulns_reports, only: [:index]
    end
    resources :host_scan_details, only: [:show]
    resources :hosts, only: [:show] do
      resources :host_services, only: [:create, :update, :destroy]
    end
    resources :metasploit, only: [:new, :create, :show] do
      resources :metasploit_reports, only: [:index]
    end
    resources :metasploit_host_views, only: [:show]
  end

  resources :engagement_statuses do
    member do
      post :accept
    end
  end
  resources :notes, only: [:create, :destroy]
  resources :on_hold_engagements, only: [:show]
  resources :activate_engagements, only: [:show]
  resources :end_engagements, only: [:update]
  resources :cwes, only: [:show, :index]
  resources :cwe_categories, only: [:show]
  resources :cwe_compound_elements, only: [:show]

  get 'download_exploit/download/:id' => 'download_exploit#download', as: :download_exploit
  get '/reports/:id/penetrations/new' => 'reports#new_penetration', as: :add_new_penetration
  delete '/reports/:id/penetrations/:penetration_id' => 'reports#remove_penetration', as: :remove_penetration
  get 'reports/:id/pdf' => 'reports#get_pdf', as: :get_pdf

  root 									 'static_pages#home'
  get 'signup'				=> 'users#new'
  get	'admin'					=> 'settings#edit'
  get 'login'		  		=> 'sessions#new'

  get 'users/get_stats'			 => 'users#get_stats'
  get 'user/:id/reset_password' => 'users#reset_password', as: :reset_user_password

  post 'login' 		 			=> 'sessions#create'
  post 'join'           => 'teams#join'
  post 'remove_member'  => 'teams#remove_member'

  delete 'logout'					=> 'sessions#destroy'

  patch 'settings' => 'settings#update'
  resources :teams do
    get 'add_members'
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    collection do
      get 'find_users'
    end
  end
  resources :users
  resources :teams
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/engagements/:engagement_id/hosts/:host_id/evidences/list' => 'evidences#list'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/upload' => 'evidences#upload'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/rename' => 'evidences#rename'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/copy' => 'evidences#copy'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/move' => 'evidences#move'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/remove' => 'evidences#remove'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/edit' => 'evidences#edit'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/get_content' => 'evidences#get_content'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/create_folder' => 'evidences#create_folder'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download' => 'evidences#download'
  get '/engagements/:engagement_id/hosts/:host_id/evidences/download_multiple' => 'evidences#download_multiple'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/compress' => 'evidences#compress'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/extract' => 'evidences#extract'
  post '/engagements/:engagement_id/hosts/:host_id/evidences/permissions' => 'evidences#permissions'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/report.rb
class Report < ActiveRecord::Base

  serialize :options, Hash

  belongs_to :user
  belongs_to :customer

  belongs_to :engagement

  has_many :screenshots, dependent: :destroy
  accepts_nested_attributes_for :screenshots

  def self.severity_levels
    {
        'CRITICAL' => :critical,
        'HIGH' => :high,
        'MEDIUM' => :medium,
        'LOW' => :low,
        'NOTE' => :note
    }
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :logged_in_user
  before_action :set_report, only: [:show, :edit, :update, :destroy, :get_pdf, :new_penetration, :remove_penetration]

  # GET /reports
  # GET /reports.json
  def index
    if current_user.admin?
      @reports = Report.all
    else
      @reports = Report.where(user: current_user)
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
    @report.options['penetrations'] = {}
    @report.options['penetrations'][SecureRandom.uuid] = {}


    vulnerability_ids = @report.options['penetrations'].keys
    @screenshots = Screenshot.where(vulnerability_id: vulnerability_ids)
    @report.user = current_user
    @report.save!
    redirect_to edit_report_path(@report)
  end

  def new_penetration
    respond_to do |format|
      @existing_penetration = {}
      @vulnerability_id = SecureRandom.uuid

      vulnerability_ids = @report.options['penetrations'].keys
      @screenshots = Screenshot.where(vulnerability_id: vulnerability_ids)

      format.js { render :new_penetration }
    end
  end

  def remove_penetration
    @report.options[:penetrations].delete(params[:penetration_id])
    @report.save!
    render nothing: true
  end

  # GET /reports/1/edit
  def edit
    vulnerability_ids = @report.options['penetrations'].keys
    @screenshots = Screenshot.where(vulnerability_id: vulnerability_ids)
    @engagement = @report.engagement
  end

  def get_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'New_Report', footer: {right: '[page]'}
      end
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.user = current_user

    respond_to do |format|
      if @report.save
        save_report_audit
        format.html { redirect_to reports_url, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|

      attributes = report_params
      attributes[:customer] = Customer.find_or_initialize_by(name: attributes[:customer]) if attributes[:customer].present?
      if @report.update(attributes)
        save_report_audit
        format.html { redirect_to reports_url, notice: 'Report was successfully updated.' }
        format.pdf { render :show, status: :ok, location: @report }
      else
        format.html { render reports_url }
        format.pdf { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def save_report_audit
    report = ReportPdf.new
    report.set_options(@report.options)
    report.set_screenshots(Screenshot.where(report_id: @report.id))

    pdf = report.generate!
    timestamp = Time.now.strftime('%F_%T')

    report_name = !@report.options['report_name'].blank? ? @report.options['report_name'] : "untitled_report_#{timestamp}"

    save_path = Rails.root.join('pdfs',"#{current_user.fname}_#{current_user.lname}_#{current_user.id}", report_name)
    FileUtils.mkdir_p save_path

    file_name = "#{timestamp}_report.pdf"
    File.open(save_path.join(file_name), 'wb') do |file|
      file << pdf
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
    if @report.user != current_user
      redirect_to reports_path, notice: 'You do not have access to that report.'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit!
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def make_name_tag(field, vulnerability_id)
    "report[options][penetrations][#{vulnerability_id.to_s}][#{field}]"
  end

  def make_absolute_url(str)
  	formated_str = ""
    if str.include? "<img"
  		formated_str = str.insert(str.index("<img")+17, request.base_url)
  	else
  		formated_str = str
  	end
  	return formated_str
  end

  def add_severity_class(severity)
  	case severity
  	when "critical"
  		return "critical"
  	when "high"
  		return "high"
  	when "medium"
  		return "medium"
  	when "low"
  		return "low"
  	when "info"
  		return "info"
  	end
  end
end

app/views/reports/_example_text.erb
<div class="example-text">
  <span class="example-header">Example: </span><p style="white-space: pre-line;"><%= ReportExampleText.send(example) %></p>
</div>

app/views/reports/_form.html.erb
<a href="#hideall" onclick="hideAll()">Hide All</a>

<p>
<p> Note: The PDF generation supports bullet points in the same way as HTML bullet lists, with one li entry per line.</p>

<%= form_for(@report) do |f| %>
    <% if @report.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

          <ul>
            <% @report.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.select :engagement_id, current_user.engagements.where_pending.collect {|e| [e.engagement_name, e.id] }.unshift(["Select Engagement", nil])%>
    </div>

    <div class="field form-group">
      <%= f.label :user_name, "Tester Name" %><br>
      <%= f.select :user_id, [@report.user].collect { |u| [u.fname, u.id] }  %>
    </div>

    <%= f.fields_for :options, OpenStruct.new(f.object.options || {}) do |f2| %>

        <div class="field form-group">
          <%= f2.label :report_name %><br>
          <%= f2.text_field :report_name, class: 'form-control' %>
        </div>

        <div class="field form-group">
          <%= f2.label "Customer" %><br>
          <%= f.autocomplete_field :customer, autocomplete_customer_name_customers_path %>
        </div>

        <%= render 'show_hide', target: :introduction %>
        <div class="field form-group">
          <%= f2.label :introduction %><br>
          <div class="introduction_toggle">
            <%= render "example_text", example: :introduction %>
            <%#= f2.text_area :introduction, rows: 4, class: 'form-control' %>
            <%= f2.cktext_area :introduction, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :objective %>
        <div class="field form-group">
          <%= f2.label :objective %><br>
          <div class="objective_toggle">
            <%= render "example_text", example: :objective %>
            <%= f2.cktext_area :objective, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :requirements %>
        <div class="field form-group">
          <%= f2.label :requirements %><br>
          <div class="requirements_toggle">
            <%= render "example_text", example: :requirements %>
            <%= f2.cktext_area :requirements, rows: 4, class: 'form-control'  %>
          </div>
        </div>

        <%= render 'show_hide', target: :high_level_summary %>
        <div class="field form-group">
          <%= f2.label :high_level_summary %><br>
          <div class="high_level_summary_toggle">
            <%= render "example_text", example: :high_level_summary %>
            <%= f2.cktext_area :high_level_summary, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :recommendations %>
        <div class="field form-group">
          <%= f2.label :recommendations %><br>
          <div class="recommendations_toggle">
            <%= render "example_text", example: :recommendations %>
            <%= f2.cktext_area :recommendations, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :risk_rating %>
        <div class="field form-group">
          <%= f2.label :risk_rating %><br>
          <div class="risk_rating_toggle">
            <%= render "example_text", example: :risk_rating %>
            <%= f2.cktext_area :risk_rating, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :information_gathering %>
        <div class="field form-group">
          <%= f2.label :information_gathering %><br>
          <div class="information_gathering_toggle">
            <%= render "example_text", example: :information_gathering %>
            <%= f2.cktext_area :information_gathering, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :penetrations %>
        <div>
          <%= f2.label :penetrations, "Successful Penetrations" %>
          <%= render "example_text", example: :penetrations %>

          <%= f2.fields_for :penetrations, OpenStruct.new(f2.object.penetrations || {}) do |f3| %>
              <%= render 'penetrations', f: f3, top_level_form: f %>
          <% end %>
        </div>

        <%= render 'show_hide', target: :post_exploitation %>
        <div class="field form-group">
          <%= f2.label :post_exploitation %>
          <div class="post_exploitation_toggle">
            <%= render "example_text", example: :post_exploitation %>
            <%= f2.cktext_area :post_exploitation, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :house_cleaning %>
        <div class="field form-group">
          <%= f2.label :house_cleaning %>
          <div class="house_cleaning_toggle">
            <%= render "example_text", example: :house_cleaning %>
            <%= f2.cktext_area :house_cleaning, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <%= render 'show_hide', target: :additional_items %>
        <div class="field form-group">
          <%= f2.label :additional_items %>
          <div class="additional_items_toggle">
            <%= render "example_text", example: :additional_items %>
            <%= f2.cktext_area :additional_items, rows: 4, class: 'form-control' %>
          </div>
        </div>

        <div class="actions">
          <%= f2.submit 'Update Report', class: 'btn btn-primary' %>
          <%= link_to 'Back', reports_path, class: 'btn btn-primary' %>
        </div>
    <% end %>
<% end %>

<script type="text/javascript">
  function hideAll() {
    var targets = [];
    $('.show-hide').each(function(index, toggle) {
      targets.push(toggle.attributes['data-target'].value);
    });
    for (var i = 0; i < targets.length; i++) {
      setVisiblity(targets[i], "false");
    }
  }
  function getTarget(target) {
    input = $('.' + target + '_toggle' );
    return input;
  }
  function toggle(target) {
    input = getTarget(target);
    input.toggle();
    sessionStorage.setItem(target, input.is(':visible'))
  }
  function setVisiblity(target, shouldBeVisibile) {
    shouldBeVisibile === "true" ? getTarget(target).show() : getTarget(target).hide()
  }
  var i = sessionStorage.length;
  while(i--) {
    var key = sessionStorage.key(i);
    setVisiblity(key, sessionStorage.getItem(key))
  }
</script>

app/views/reports/_new_penetration_markup.html.erb
<!-- this allows us to use a simple link_to styled like a button -->
<style>
.visited-white:visited {
  color: white;
}
</style>

<div class="field well">
  <div class="form-group">
    <%= label_tag :vulnerability %>
    <%= text_field_tag make_name_tag('vulnerability', vulnerability_id), existing_penetration[:vulnerability], class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :system_vulnerable %>
    <%= text_field_tag make_name_tag('system_vulnerable', vulnerability_id), existing_penetration[:system_vulnerable], class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :vulnerability_explanation %>
    <%= cktext_area make_name_tag('vulnerability_explanation', vulnerability_id), existing_penetration[:vulnerability_explanation], rows: 4, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :vulnerability_fix %>
    <%= cktext_area make_name_tag('vulnerability_fix', vulnerability_id), existing_penetration[:vulnerability_fix], rows: 4, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :severity %>
    <%= select_tag make_name_tag('severity', vulnerability_id), options_for_select(Report.severity_levels), class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :proof_of_concept_code %>
    <%= text_area_tag make_name_tag('proof_of_concept_code', vulnerability_id), existing_penetration[:proof_of_concept_code], rows: 10, class: 'form-control' %>
  </div>


  <%= label_tag 'Screenshots' %>
  <div>
    <% @screenshots.where(vulnerability_id: vulnerability_id.to_s).each do |screenshot| %>
    <div class="screenshot">
      <%= image_tag screenshot.file.url %>
      <p><%= screenshot.caption %></p>
      <%= link_to 'Delete Screenshot', screenshot_path(screenshot), method: :delete, class: 'delete btn btn-danger' %>
    </div>
    <% end %>

    <% if @screenshots.where(vulnerability_id: vulnerability_id.to_s).count.zero? %>
      <p>You don't have any screenshots for this penetration yet.</p>
    <% end %>
  </div>

  <div>
    <br />
    <%= link_to 'Add a screenshot', new_screenshot_path(report_id: report.id, vulnerability_id: vulnerability_id.to_s), target: '_blank', class: 'button btn btn-success visited-white mBot9 vTop' %>
    <%= link_to 'Remove this penetration', remove_penetration_path(report.id, vulnerability_id.to_s), class: 'remove-penetration button btn btn-warning visited-white',  data: { penetration_id: vulnerability_id } %>
  </div>
</div>

app/views/reports/_penetrations.html.erb
<div class="penetrations penetrations_toggle">
  <% f.object.to_h.each do |vulnerability_id, penetration| %> <!-- enumerated services (i.e., each of the servers we have found)-->
    <%= f.fields_for vulnerability_id do |penetration_instance| %>
    <hr>
      <%= render 'new_penetration_markup', report: @report, existing_penetration: penetration, vulnerability_id: vulnerability_id %>
    <% end %>
    <% end %>
</div>

<br>
  <%= link_to 'Add New Successful Penetration Log', add_new_penetration_path(@report.id), remote: true, class: 'btn btn-primary' %>
<hr>

<script type="text/javascript">
  $('a.delete').click (function(){
    if(confirm("Are you sure?")){
      var screenshot = $(this).closest("div").get(0);
      $.post(this.href, {_method:'delete'}, null, "script");
      $(screenshot).hide();
      return false;
    } else {
      return false;
    }
  });

  $('.remove-penetration').click( function(e) {
    e.preventDefault();
    if (confirm("Are you sure? This will permanenty delete this penetration log.")) {
      var penetration_id = $(this).data('penetration-id');
      $.post(this.href, {_method:'delete'}, null, "script");
      $(this).closest(".well").hide();
      return false;
    } else {
      return false;
    }
  });
</script>

app/views/reports/_report.html.erb
<span><strong><%= "#{report.user.fname} #{report.user.lname} | #{report.user.username}" if current_user.admin? %></strong></span><br>
<span><%= report.options['report_name'] %> for <%= report.customer %></span><br>
<span><%= report.updated_at.to_formatted_s(:long)  %></span><br>
<div class="listingLink">
  <% unless customer_view %>
    <span>
      <%= link_to edit_report_path(report) do %>
        <i class="glyphicon glyphicon-pencil"></i> Edit
      <% end %>
    </span>
    <span>
      <%= link_to report, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="glyphicon glyphicon-trash"></i> Destroy
      <% end %>
    </span>
  <% end %>
  <span>
    <%= link_to get_pdf_path(report, format: :pdf) do %>
      <i class="glyphicon glyphicon-save"></i> Download as PDF
    <% end %>
  </span>
</div>
<hr>

app/views/reports/_show_hide.html.erb
<a href="#null" class="show-hide" data-target="<%= target.to_s %>" tabindex="-1" onclick="toggle('<%= target.to_s %>')">Show/Hide</a>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

app/views/reports/footer.pdf.erb
<html>
  <head>
    <script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = decodeURIComponent(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
      }
    </script>
  </head>
  <body onload="number_pages()">
    Page <span class="page"></span> of <span class="topage"></span>
  </body>
</html>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<% @reports.each do |report| %>
    <%= render 'reports/report', { report:report, customer_view: false } %>
<% end %>

<br>
<br>

<%= link_to 'New Report', new_report_path, class: "btn btn-primary" %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

app/views/reports/new_penetration.js.erb
$('.penetrations').append("<%=j render partial: 'new_penetration_markup', locals: { existing_penetration: @existing_penetration, vulnerability_id: @vulnerability_id, report: @report, screenshots: @screenshots } %>");

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Options:</strong>
  <%= @report.options %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>